import { auth, db } from './firebase.js'; import { collection, addDoc, onSnapshot, doc, deleteDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js'; import { uploadToCloudinary } from './cloudinary.js'; import { qs, toast } from './ui.js'; import { isAdmin, isKontributor } from './roles.js';
const grid=qs('#produkGrid'), btnTambah=qs('#btnTambahProduk'), modal=qs('#modalProduk'), simpan=qs('#simpanProduk'), batal=qs('#batalProduk');
if(isKontributor()){ btnTambah.style.display=''; } btnTambah&&btnTambah.addEventListener('click',()=> modal.hidden=false); batal&&batal.addEventListener('click',()=> modal.hidden=true);
const money=n=>Number(n||0).toLocaleString('id-ID');
onSnapshot(collection(db,'pasar'), (snap)=>{ grid.innerHTML=''; snap.docs.sort((a,b)=>(b.data().timestamp||0)-(a.data().timestamp||0)).forEach(d=>{ const p=d.data(); const card=document.createElement('div'); card.className='produk-card'; card.innerHTML=`<img src="${p.foto||'/assets/icons/kt.svg'}" alt="${p.nama||''}"><div class="pad"><h4>${p.nama||''}</h4><p>Rp ${money(p.harga)}</p><p class="desc">${p.deskripsi||''}</p><a class="btn-wa" target="_blank" href="https://wa.me/${p.wa}?text=${encodeURIComponent('Halo, saya ingin membeli '+(p.nama||'produk')+' (Rp '+money(p.harga)+')')}">🛒 Beli via WhatsApp</a>${(auth.currentUser&&(auth.currentUser.uid===p.owner||isAdmin()))?'<button class="btn-del" data-id="'+d.id+'">🗑️</button>':''}</div>`; grid.append(card); }); grid.querySelectorAll('.btn-del').forEach(b=> b.onclick=async(e)=>{ if(confirm('Hapus produk ini?')) await deleteDoc(doc(db,'pasar', e.currentTarget.dataset.id)); }); });
simpan&&simpan.addEventListener('click', async ()=>{ const nama=qs('#namaProduk').value.trim(), harga=Number(qs('#hargaProduk').value), deskripsi=qs('#deskripsiProduk').value.trim(), wa=qs('#waProduk').value.trim(), file=qs('#fotoProduk').files[0]; if(!nama||!harga||!file||!wa) return toast('Lengkapi nama, harga, foto, dan WA'); try{ const foto=await uploadToCloudinary(file,'pasar'); await addDoc(collection(db,'pasar'),{nama,harga,deskripsi,wa,foto,owner:auth.currentUser?.uid||null,timestamp:Date.now()}); toast('Produk ditambahkan'); qs('#namaProduk').value=''; qs('#hargaProduk').value=''; qs('#deskripsiProduk').value=''; qs('#waProduk').value=''; qs('#fotoProduk').value=''; modal.hidden=true; }catch(e){ alert(e.message);} });
// counters
import { onSnapshot as onS, collection as coll } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
onS(coll(db,'pasar'), s=> qs('#countPasar').textContent=s.size);
onS(coll(db,'berita'), s=> qs('#countBerita').textContent=s.size);
onS(coll(db,'kas'), s=>{ let masuk=0,keluar=0; s.forEach(x=>{ const d=x.data(); if(d.tipe==='keluar') keluar+=Number(d.jumlah||0); else masuk+=Number(d.jumlah||0); }); qs('#countKas').textContent='Rp '+Number(masuk-keluar).toLocaleString('id-ID'); });
